### ISSUE TITLE
Missing pyMCDS_cells python module

### ISSUE THREAD

**Issue by guaje** [rheiland/fury_tumor#1]
Hi Randy

I'm trying to run your demo, however, I can't find this python module:

https://github.com/rheiland/fury_tumor/blob/ad8d9e5f9e1f44bbcd1eb81303d58870dcf77168/tumor_vis1.py#L2

Perhaps, the closest solution I found is this one:

http://www.mathcancer.org/blog/python-loader/

But it seems it works in a different way because when I try to load the data (`mcds = pyMCDS('output00000001.xml', '.')`) it throws the following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'initial_mesh0.mat'`

Can you point me to the right way to load the data?

**Comment by rheiland** [comment]
Argh, just committed it. Sorry.

**Comment by guaje** [comment]
Thanks! It's working now. We're going to add the clipping plane and also replace the sphere actor by the billboard actor.

Closing this issue now.
